### ISSUE TITLE
Create Post Button

### ISSUE THREAD

**Issue by auntviv** [nss-day-cohort-52/giffygram-dream-tigers#21]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
no current behavior, refers to #12 

* **What is the expected behavior?**
Button will generate post form.

* **What is the motivation / use case for changing the behavior?**
On clicking post button, generate post form. 3 fields (name description url, see posts table) and a save button.

**Comment by Dervalanana** [comment]
updating details, post form has been created, will link to post button in my current PR
